const ErrorCodes = {
  INVALID_ROUTE: 'INVALID_ROUTE',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_FILE_NAME: 'INVALID_FILE_NAME',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SHARP_PROCESSING_ERROR: 'SHARP_PROCESSING_ERROR'
}

export default ErrorCodes
